
빅분기 3회 실기

In [ ]:
import pandas as pd

df = pd.read_csv('path')

In [ ]:
# 1-1
# 결측치 제거, 앞에서부터 70%, 1 사분위
df = df.dropna()
print(df.shape)
df = df.iloc[:int(len(df)*0.7), :]
print(int(df['age'].quantile(.25)))

In [ ]:
# 1-2
# 2000년 평균보다 큰 값 갯수

m = df.loc[2000].mean()
print(sum(df.loc[2000, :]>m))

In [6]:
# 중앙값
a = [7, 9, 16, 36, 39, 45, 45, 46, 48, 51]
import numpy as np

x = np.array(a)
me = np.median(a)
print(me)
# 짝수개면 두 개의 숫자 평균

42.0

In [48]:
# 1-3
import pandas as pd
df = pd.read_csv('/home/kbae/bigdata_analytics/FL_insurance_sample.csv')
df

,policyID,statecode,county,eq_site_limit,hu_site_limit,fl_site_limit,fr_site_limit,tiv_2011,tiv_2012,eq_site_deductible,hu_site_deductible,fl_site_deductible,fr_site_deductible,point_latitude,point_longitude,line,construction,point_granularity
0,119736,FL,CLAY COUNTY,498960.0,498960.00,498960.0,498960.0,498960.00,792148.90,0.0,9979.2,0.0,0,30.102261,-81.711777,Residential,Masonry,1
1,448094,FL,CLAY COUNTY,1322376.3,1322376.30,1322376.3,1322376.3,1322376.30,1438163.57,0.0,0.0,0.0,0,30.063936,-81.707664,Residential,Masonry,3
2,206893,FL,CLAY COUNTY,190724.4,190724.40,190724.4,190724.4,190724.40,192476.78,0.0,0.0,0.0,0,30.089579,-81.700455,Residential,Wood,1
3,333743,FL,CLAY COUNTY,0.0,79520.76,0.0,0.0,79520.76,86854.48,0.0,0.0,0.0,0,30.063236,-81.707703,Residential,Wood,3
4,172534,FL,CLAY COUNTY,0.0,254281.50,0.0,254281.5,254281.50,246144.49,0.0,0.0,0.0,0,30.060614,-81.702675,Residential,Wood,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36629,404309,FL,PINELLAS COUNTY,0.0,88722.00,0.0,88722.0,88722.00,155065.65,0.0,0.0,0.0,0,28.122885,-82.770218,Residential,Wood,3
36630,465875,FL,PINELLAS COUNTY,1297057.5,1297057.50,1297057.5,1297057.5,1297057.50,1577500.79,0.0,0.0,0.0,0,28.080900,-82.758800,Residential,Masonry,1
36631,791209,FL,PINELLAS COUNTY,173286.9,173286.90,0.0,0.0,173286.90,205527.97,0.0,0.0,0.0,0,28.110550,-82.766360,Residential,Wood,4
36632,322627,FL,PINELLAS COUNTY,1499781.6,1499781.60,0.0,0.0,1499781.60,1768782.43,0.0,0.0,0.0,0,28.089415,-82.697411,Residential,Masonry,3
36633,398149,FL,PINELLAS COUNTY,373488.3,373488.30,0.0,0.0,373488.30,596003.67,0.0,0.0,0.0,0,28.064440,-82.774590,Residential,Masonry,1

In [53]:
print(df.iloc[3, 4])

79520.76

In [56]:
df.shape

(36634, 18)

In [57]:
df.info

<bound method DataFrame.info of        policyID statecode           county  eq_site_limit  hu_site_limit  \
0        119736        FL      CLAY COUNTY       498960.0      498960.00
1        448094        FL      CLAY COUNTY      1322376.3     1322376.30
2        206893        FL      CLAY COUNTY       190724.4      190724.40
3        333743        FL      CLAY COUNTY            0.0       79520.76
4        172534        FL      CLAY COUNTY            0.0      254281.50
...         ...       ...              ...            ...            ...
36629    404309        FL  PINELLAS COUNTY            0.0       88722.00
36630    465875        FL  PINELLAS COUNTY      1297057.5     1297057.50
36631    791209        FL  PINELLAS COUNTY       173286.9      173286.90
36632    322627        FL  PINELLAS COUNTY      1499781.6     1499781.60
36633    398149        FL  PINELLAS COUNTY       373488.3      373488.30

       fl_site_limit  fr_site_limit    tiv_2011    tiv_2012  \
0           498960.0       498960.0   498960.00   792148.90
1          1322376.3      1322376.3  1322376.30  1438163.57
2           190724.4       190724.4   190724.40   192476.78
3                0.0            0.0    79520.76    86854.48
4                0.0       254281.5   254281.50   246144.49
...              ...            ...         ...         ...
36629            0.0        88722.0    88722.00   155065.65
36630      1297057.5      1297057.5  1297057.50  1577500.79
36631            0.0            0.0   173286.90   205527.97
36632            0.0            0.0  1499781.60  1768782.43
36633            0.0            0.0   373488.30   596003.67

       eq_site_deductible  hu_site_deductible  fl_site_deductible  \
0                     0.0              9979.2                 0.0
1                     0.0                 0.0                 0.0
2                     0.0                 0.0                 0.0
3                     0.0                 0.0                 0.0
4                     0.0                 0.0                 0.0
...                   ...                 ...                 ...
36629                 0.0                 0.0                 0.0
36630                 0.0                 0.0                 0.0
36631                 0.0                 0.0                 0.0
36632                 0.0                 0.0                 0.0
36633                 0.0                 0.0                 0.0

       fr_site_deductible  point_latitude  point_longitude         line  \
0                       0       30.102261       -81.711777  Residential
1                       0       30.063936       -81.707664  Residential
2                       0       30.089579       -81.700455  Residential
3                       0       30.063236       -81.707703  Residential
4                       0       30.060614       -81.702675  Residential
...                   ...             ...              ...          ...
36629                   0       28.122885       -82.770218  Residential
36630                   0       28.080900       -82.758800  Residential
36631                   0       28.110550       -82.766360  Residential
36632                   0       28.089415       -82.697411  Residential
36633                   0       28.064440       -82.774590  Residential

      construction  point_granularity
0          Masonry                  1
1          Masonry                  3
2             Wood                  1
3             Wood                  3
4             Wood                  1
...            ...                ...
36629         Wood                  3
36630      Masonry                  1
36631         Wood                  4
36632      Masonry                  3
36633      Masonry                  1

[36634 rows x 18 columns]>

In [58]:
df.isnull().sum()

policyID              0
statecode             0
county                0
eq_site_limit         0
hu_site_limit         0
fl_site_limit         0
fr_site_limit         0
tiv_2011              0
tiv_2012              0
eq_site_deductible    0
hu_site_deductible    0
fl_site_deductible    0
fr_site_deductible    0
point_latitude        0
point_longitude       0
line                  0
construction          0
point_granularity     0
dtype: int64

In [59]:
df.describe()

,policyID,eq_site_limit,hu_site_limit,fl_site_limit,fr_site_limit,tiv_2011,tiv_2012,eq_site_deductible,hu_site_deductible,fl_site_deductible,fr_site_deductible,point_latitude,point_longitude,point_granularity
count,36634.000000,3.663400e+04,3.663400e+04,3.663400e+04,3.663400e+04,3.663400e+04,3.663400e+04,3.663400e+04,3.663400e+04,36634.000000,36634.000000,36634.000000,36634.000000,36634.000000
mean,548661.937189,7.314780e+05,2.074348e+06,6.646009e+05,9.911724e+05,2.172875e+06,2.571004e+06,7.787908e+02,7.037985e+03,192.453210,26.483594,28.087477,-81.903565,1.640907
std,259912.926494,1.752300e+07,1.964150e+07,1.746114e+07,1.767178e+07,2.015015e+07,2.036777e+07,4.787979e+04,9.582593e+04,8037.713716,4702.740932,1.647734,1.809066,1.070561
min,100074.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,9.000000e+01,7.337000e+01,0.000000e+00,0.000000e+00,0.000000,0.000000,24.547514,-87.447290,1.000000
25%,323647.750000,0.000000e+00,4.248106e+04,0.000000e+00,0.000000e+00,4.562415e+04,5.401351e+04,0.000000e+00,0.000000e+00,0.000000,0.000000,26.471996,-82.439331,1.000000
50%,548525.000000,0.000000e+00,1.926911e+05,0.000000e+00,0.000000e+00,2.021051e+05,2.416310e+05,0.000000e+00,0.000000e+00,0.000000,0.000000,28.057077,-81.585700,1.000000
75%,774252.000000,0.000000e+00,9.163381e+05,0.000000e+00,5.741010e+04,9.465821e+05,1.128871e+06,0.000000e+00,0.000000e+00,0.000000,0.000000,29.623005,-80.372910,3.000000
max,999971.000000,2.160000e+09,2.160000e+09,2.160000e+09,2.160000e+09,2.160000e+09,1.701000e+09,6.273765e+06,7.380000e+06,450000.000000,900000.000000,30.989820,-80.033257,7.000000

In [61]:
df['eq_site_limit'].value_counts()

0.0          27593
450.0          183
270.0          113
540.0           75
3825.0          74
             ...
128520.0         1
596700.0         1
1682225.1        1
119091.6         1
373488.3         1
Name: eq_site_limit, Length: 5961, dtype: int64

In [30]:
import pandas as pd

df = pd.DataFrame({
                    'A': [
                        'jim',
                        'jim',
                        'jim',
                        'jim',
                        'sal',
                        'tom',
                        'tom',
                        'sal',
                        'sal'],
                    'B': [
                        'a',
                        'b', 
                        'a', 
                        'b', 
                        'b', 
                        'b', 
                        'a', 
                        'a', 
                        'b']
                    })  

freq = df.groupby(['A']).count() 
freq = df.groupby(['A']).count() 
print(freq)

     B
A
jim  4
sal  3
tom  2

In [55]:
a = 100
import math
print(math.sqrt(a))

10.0

In [ ]:
n_train = train.select_dtypes(include=['number']).copy()
c_train = train.select_dtypes(exclude=['number']).copy()